# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd4c7dd0a988e4b3a720c1b65cc9b3c2f641a57f6f553d97b8c3ac5760b051148e9bd708c9ea9cb1c87698aea531872217b1b58664f6b2692dc7aa5d08ea6e6e

test:
  secret_key_base: 42d7c5e8a5e5b1aa45cd34f0a85c3b9e16446c7606c75cb0c7dcc85c63bc855678d00908ac1cd7fc21ddaf34542996fc50f7c9a6459e061637d280d9b5767c56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
